name: CD-Liara
on:
  push:
    branches:
      - fix/AutomatedTest
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: 
          npm ci
      - run:
          npm test --coverage


  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npx @liara/cli@5 deploy --platform=node --port=8000 --app="nitroplus" --api-token="$LIARA_TOKEN" --no-app-logs
